name: mac_queries
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  firebase_core: ^2.31.0
  firebase_database: ^10.5.5
  cloud_firestore: ^4.17.3
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  url_launcher: ^6.2.6
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  fake_async: ^1.3.1
  build_runner: ^2.4.9
  mockito: ^5.4.4
  firebase_auth_mocks: ^0.13.0
  firebase_database_mocks: ^0.6.1
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
