// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFlkEVlehc_jILiVy6FRlYkzhCRtIs_iU',
    appId: '1:158701041386:web:90386e5b5b4c3377ac4993',
    messagingSenderId: '158701041386',
    projectId: 'macq-a58c9',
    authDomain: 'macq-a58c9.firebaseapp.com',
    storageBucket: 'macq-a58c9.appspot.com',
    measurementId: 'G-5SH70670BQ',
    databaseURL: 'https://macq-a58c9-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdlGeZ8xTR4u7yIjoMBZzvHLGU9i0DC_k',
    appId: '1:158701041386:android:1dbdcec979e22d5bac4993',
    messagingSenderId: '158701041386',
    projectId: 'macq-a58c9',
    storageBucket: 'macq-a58c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS902sOWO2znPnr4TAb3VvBPvbN2rfrKg',
    appId: '1:158701041386:ios:d158a0f52e7164e9ac4993',
    messagingSenderId: '158701041386',
    projectId: 'macq-a58c9',
    storageBucket: 'macq-a58c9.appspot.com',
    iosBundleId: 'com.example.macQueries',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS902sOWO2znPnr4TAb3VvBPvbN2rfrKg',
    appId: '1:158701041386:ios:d158a0f52e7164e9ac4993',
    messagingSenderId: '158701041386',
    projectId: 'macq-a58c9',
    storageBucket: 'macq-a58c9.appspot.com',
    iosBundleId: 'com.example.macQueries',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFlkEVlehc_jILiVy6FRlYkzhCRtIs_iU',
    appId: '1:158701041386:web:5b66264c2a5fdbcdac4993',
    messagingSenderId: '158701041386',
    projectId: 'macq-a58c9',
    authDomain: 'macq-a58c9.firebaseapp.com',
    storageBucket: 'macq-a58c9.appspot.com',
    measurementId: 'G-0ZXK512FPG',
  );
}
